spring:  
  datasource:
    url: "jdbc:mysql://localhost/besteffort1pc"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.jdbc.Driver"
  rabbitmq:
    host: "localhost"
    port: 5672
